/**
 * Explicit icon registry.
 *
 * Content files reference icons by name (e.g. `icon: "ShieldCheck"`). Importing
 * each icon by name here keeps the bundle tree-shakeable — a dynamic
 * `lucide-react` lookup would pull in the entire library.
 *
 * This module deliberately exports no components, so `lib/icons.jsx` can stay a
 * pure component module and keep Fast Refresh working.
 */
import {
  Activity,
  Apple,
  Atom,
  Award,
  Baby,
  BadgeCheck,
  Ban,
  Blocks,
  BookMarked,
  BookOpen,
  Brain,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarX,
  Compass,
  Droplets,
  FileText,
  FlaskConical,
  Flower2,
  GlassWater,
  Globe,
  GraduationCap,
  Hand,
  Heart,
  HeartHandshake,
  Leaf,
  Lightbulb,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Microscope,
  Moon,
  Music,
  Network,
  Palette,
  PartyPopper,
  Pencil,
  Puzzle,
  Radio,
  Rocket,
  Settings,
  Shapes,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Tent,
  Trees,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  UtensilsCrossed,
  Waves,
} from "lucide-react";

const REGISTRY = {
  Activity,
  Apple,
  Atom,
  Award,
  Baby,
  BadgeCheck,
  Ban,
  Blocks,
  BookMarked,
  BookOpen,
  Brain,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarX,
  Compass,
  Droplets,
  FileText,
  FlaskConical,
  Flower2,
  GlassWater,
  Globe,
  GraduationCap,
  Hand,
  Heart,
  HeartHandshake,
  Leaf,
  Lightbulb,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Microscope,
  Moon,
  Music,
  Network,
  Palette,
  PartyPopper,
  Pencil,
  Puzzle,
  Radio,
  Rocket,
  Settings,
  Shapes,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Tent,
  Trees,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  UtensilsCrossed,
  Waves,
};

/**
 * Resolve a registry name to its (module-level, stable) component.
 * Falls back to a neutral mark so a typo never breaks a page.
 */
export function getIcon(name) {
  return REGISTRY[name] || Sparkles;
}
